### ISSUE TITLE
 java.lang.IllegalArgumentException: 237 is not a valid offset for file while sonar.sourceEncoding property is defined

### ISSUE THREAD

**Issue by jfallot** [racodond/sonar-jproperties-plugin#45]
Hello,

I am getting such error since the upgrade to version 2.0 (under SonarQube 5.6 with Java 1.8.0_60).
I made several tries with various sonar.sourceEncoding values (UTF-8, ISO-8859-1) but without success.

`ERROR: Error during SonarQube Scanner execution
org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: <http://srcstat/jenkins/job/Sonar%20-%20VistaMart/ws/vistamart/tools/src/com/infovista/es/djinns/ui/solution.properties>
    at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:131)
    at org.sonar.plugins.jproperties.JavaPropertiesSquidSensor.execute(JavaPropertiesSquidSensor.java:90)
    at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
    at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
    at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
    at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
    at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
    at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
    at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234)
    at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
    at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
    at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
    at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
    at com.sun.proxy.$Proxy0.execute(Unknown Source)
    at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240)
    at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
    at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
    at org.sonarsource.scanner.cli.Main.execute(Main.java:72)
    at org.sonarsource.scanner.cli.Main.main(Main.java:60)
Caused by: java.lang.IllegalArgumentException: Unable to highlight file [moduleKey=com.infovista:vistamart:tools, relative=src/com/infovista/es/djinns/ui/solution.properties, basedir=<http://srcstat/jenkins/job/Sonar%20-%20VistaMart/ws/vistamart/tools]>
    at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:86)
    at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:36)
    at org.sonar.jproperties.ast.visitors.SyntaxHighlighterVisitor.visitNode(SyntaxHighlighterVisitor.java:76)
    at com.sonar.sslr.impl.ast.AstWalker.visitNode(AstWalker.java:114)
    at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:85)
    at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
    at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
    at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
    at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
    at com.sonar.sslr.impl.ast.AstWalker.walkAndVisit(AstWalker.java:69)
    at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:110)
    ... 32 more
Caused by: java.lang.IllegalArgumentException: 237 is not a valid offset for file [moduleKey=com.infovista:vistamart:tools, relative=src/com/infovista/es/djinns/ui/solution.properties, basedir=<http://srcstat/jenkins/job/Sonar%20-%20VistaMart/ws/vistamart/tools].> Max offset is 236
    at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
    at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:270)
    at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:265)
    at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:84)
    ... 42 more
`

**Comment by racodond** [comment]
Hi @jfallot,

Could you please send me the file to investigate?

Thank you

David

**Comment by jfallot** [comment]
Hello,

Please find the file attached.

Regards,
JF

[testcase.zip](https://github.com/racodond/sonar-jproperties-plugin/files/353743/testcase.zip)

**Comment by racodond** [comment]
Hi @jfallot,

Thanks for the file. Your issue comes from the fact that the last line of your file is missing a line ending character. If you open the file in a text editor and save it, it should fix this missing line ending character. Then, as the file will be syntactically correct , the SonarQube analysis will run fine.

Have a good day

David

**Comment by jfallot** [comment]
Hi @racodond,

Thank you for your prompt answer.

However:
- The java application using this properties file has no issue to load it
- Such error didn't occur with the previous version of the properties plugin

If I understood you well, this new version seems to introduce the requirement that a CRLF is required at the last line of the properties file, which isn't required on Java side.

Is this intentional or a side-effect of other changes of the 2.0?

Regards,
JF

**Comment by racodond** [comment]
Hi @jfallot,

> The java application using this properties file has no issue to load it

OK. Same for the SonarQube plugin: no issue about parsing this file. The issue is on syntax highlighting.

> Such error didn't occur with the previous version of the properties plugin

Hard to say. You had to update the SonarQube platform as well, not just the Java Properties plugin. Note that in previous versions of the SonarQube platform (I don't remember exactly which one, 5.x), such an issue on highlighting was just ignored and was not making the analysis crash.

> If I understood you well, this new version seems to introduce the requirement that a CRLF is required at the last line of the properties file, which isn't required on Java side.

A text file missing line endings is not a valid text file (unless you provide a link to Java documentation stating the opposite). So, you cannot expect SonarQube to cover this corner case and should fix your file.

David
