### ISSUE TITLE
Analysis fails when no custom rule is provided

### ISSUE THREAD

**Issue by nixel2007** [racodond/sonar-jproperties-plugin#56]
Hi!
I've just upgraded java-properties plugin to ~~1.21~~ 2.1 and have this error on our jenkins-ci

```
ERROR: Error during SonarQube Scanner execution
org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: org.sonar.plugins.jproperties.JavaPropertiesSquidSensor has unsatisfied dependency 'class [Lorg.sonar.plugins.jproperties.api.CustomJavaPropertiesRulesDefinition;' for constructor 'public org.sonar.plugins.jproperties.JavaPropertiesSquidSensor(org.sonar.api.batch.fs.FileSystem,org.sonar.api.batch.rule.CheckFactory,org.sonar.plugins.jproperties.api.CustomJavaPropertiesRulesDefinition[])' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@dd3977:225<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@1c27ee8:216<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@271936:11<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@8307f7:44<|
    at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:191)
    at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:110)
    at org.picocontainer.injectors.ConstructorInjector.access$100(ConstructorInjector.java:51)
    at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:331)
    at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
    at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
    at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
    at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
    at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
    at org.picocontainer.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:606)
    at org.picocontainer.DefaultPicoContainer.getComponents(DefaultPicoContainer.java:587)
    at org.sonar.core.platform.ComponentContainer.getComponentsByType(ComponentContainer.java:281)
    at org.sonar.batch.bootstrap.BatchExtensionDictionnary.completeBatchExtensions(BatchExtensionDictionnary.java:134)
    at org.sonar.batch.bootstrap.BatchExtensionDictionnary.getExtensions(BatchExtensionDictionnary.java:128)
    at org.sonar.batch.bootstrap.BatchExtensionDictionnary.getFilteredExtensions(BatchExtensionDictionnary.java:107)
    at org.sonar.batch.bootstrap.BatchExtensionDictionnary.select(BatchExtensionDictionnary.java:74)
    at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:46)
    at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
    at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
    at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
    at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
    at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
    at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
    at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
    at com.sun.proxy.$Proxy0.execute(Unknown Source)
    at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240)
    at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
    at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
    at org.sonarsource.scanner.cli.Main.execute(Main.java:72)
    at org.sonarsource.scanner.cli.Main.main(Main.java:60)
```

**Comment by nixel2007** [comment]
Runned on windows 7 slave with (jenkins) built-in sonar-scanner.

**Comment by nixel2007** [comment]
Also, looks like it can't upgrade itself properly - after restarting of sonar-server i see ~~1.20~~ 2.0 version and an update to ~~1.21~~ 2.1 button.

**Comment by grafra** [comment]
I think I have the same exception but i am using java properties version 2.1

`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.1:sonar (default-cli) on project esfbund: org.sonar.plugins.jproperties.JavaPropertiesSquidSensor has unsatisfied dependency 'class [Lorg.sonar.plugins.jproperties.api.CustomJavaPropertiesRulesDefinition;' for constructor 'public org.sonar.plugins.jproperties.JavaPropertiesSquidSensor(org.sonar.api.batch.fs.FileSystem,org.sonar.api.batch.rule.CheckFactory,org.sonar.plugins.jproperties.api.CustomJavaPropertiesRulesDefinition[])' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@e2498a3:224<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@6edb2c7b:225<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@3f33bb6f:12<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@edf4973:45<| -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:`

**Comment by nixel2007** [comment]
Ah, sorry. Yes, i mean 2.0 and 2.1 versions

**Comment by racodond** [comment]
Hi @nixel2007, Hi @grafra,

Thanks for reporting the issue. It's currently being discussed on the SonarQube Google Group: https://groups.google.com/forum/#!topic/sonarqube/4Y8vzroZeSE. So, you can follow this thread. Anyway, I'll post the output of this thread here as well.

David

**Comment by racodond** [comment]
@nixel2007, @grafra:

The issue has been fixed and an RC is now available: https://groups.google.com/forum/#!topic/sonarqube/8zu_UMiJuBg. Feel free to test and vote.

Thank you

David
